import type { Expression } from '@praat/core';

type ExpressionInput = Omit<Expression, 'region'> & { region?: Expression['region'] };

const e = (input: ExpressionInput): Expression => ({ region: 'both', ...input });

/**
 * "Speak Like a Dutch Person": the natural, spoken Dutch that textbooks leave out — with
 * who uses it, when, and how it compares to the textbook version.
 */
export const expressions: Expression[] = [
  // Greetings
  e({ id: 'expr.hoe-gaat-ie', category: 'greetings', natural: 'Hoe gaat-ie?', textbook: 'Hoe gaat het met jou?', en: "How's it going?", register: 'informal', whoUses: 'Almost everyone under 60 with friends, colleagues and peers.', when: "A casual greeting. Answer 'Goed!' or 'Prima, en met jou?'", examples: [{ nl: 'Hé Tom, hoe gaat-ie?', en: "Hey Tom, how's it going?" }], level: 'A1' }),
  e({ id: 'expr.alles-goed', category: 'greetings', natural: 'Alles goed?', textbook: 'Is alles goed met u?', en: 'All good?', register: 'informal', whoUses: 'Very common in the Netherlands and Flanders, among friends of all ages.', when: "Used almost like 'hi'. Reply 'Ja, prima! En met jou?' — it's not an invitation to list your problems.", examples: [{ nl: 'Hoi Sanne, alles goed?', en: 'Hi Sanne, all good?' }], level: 'A1' }),
  e({ id: 'expr.doei', category: 'greetings', natural: 'Doei!', textbook: 'Tot ziens.', en: 'Bye!', register: 'informal', whoUses: "Everyone in informal settings in the Netherlands. Children and teenagers double it: 'doeidoei'.", when: 'Leaving friends, colleagues and relaxed shops.', examples: [{ nl: 'Oké, doei! Tot morgen!', en: 'Okay, bye! See you tomorrow!' }], region: 'nl', level: 'A0' }),
  e({ id: 'expr.tot-zo', category: 'greetings', natural: 'Tot zo!', textbook: 'Ik zie je straks.', en: 'See you in a bit!', register: 'neutral', whoUses: 'Everyone.', when: "When you'll see the person again soon — within minutes or hours.", examples: [{ nl: 'Ik haal even koffie. Tot zo!', en: "I'm getting coffee. See you in a sec!" }], level: 'A1' }),
  e({ id: 'expr.salut', category: 'greetings', natural: 'Salut!', textbook: 'Tot ziens.', en: 'Bye! (Flanders)', register: 'informal', whoUses: 'Flemish speakers of all ages.', when: 'Mostly as a goodbye in Flanders; borrowed from French.', examples: [{ nl: 'Salut, tot morgen!', en: 'Bye, see you tomorrow!' }], region: 'be', level: 'A1' }),

  // Reactions
  e({ id: 'expr.wat-leuk', category: 'reactions', natural: 'Wat leuk!', textbook: 'Dat is heel leuk.', en: 'How nice!', register: 'neutral', whoUses: 'Everyone, all the time.', when: 'Reacting to good news, plans or stories.', examples: [{ nl: 'Ik ga naar Italië. – Wat leuk!', en: "I'm going to Italy. – How nice!" }], level: 'A1' }),
  e({ id: 'expr.echt-leuk', category: 'reactions', natural: 'Dat is echt leuk', textbook: 'Dat is very nice', en: "That's really nice", register: 'neutral', whoUses: 'Everyone.', when: "A positive reaction to almost anything. Mixing in English ('very nice') is common among learners — and young Dutch people do it too — but 'echt leuk' or 'heel leuk' sounds natural. 'Zeer' is formal and mostly written.", examples: [{ nl: 'Die film? Die is echt leuk!', en: "That film? It's really good!" }], level: 'A1' }),
  e({ id: 'expr.balen', category: 'reactions', natural: 'Balen!', textbook: 'Dat is jammer.', en: 'What a bummer!', register: 'informal', whoUses: 'Young people and adults in casual speech.', when: 'Sympathy for bad luck, or your own annoyance.', examples: [{ nl: 'Mijn fiets is gestolen. – Balen, zeg!', en: 'My bike was stolen. – What a bummer!' }], level: 'A2' }),
  e({ id: 'expr.nee-hoor', category: 'reactions', natural: 'Nee hoor', textbook: 'Nee, dat is niet zo.', en: 'No, not at all', register: 'neutral', whoUses: 'Everyone.', when: 'A friendly denial or reassurance.', examples: [{ nl: 'Stoor ik? – Nee hoor, kom binnen!', en: 'Am I disturbing you? – Not at all, come in!' }], level: 'A2' }),
  e({ id: 'expr.maakt-niet-uit', category: 'reactions', natural: 'Maakt niet uit', textbook: 'Het is voor mij niet belangrijk.', en: "Doesn't matter", register: 'neutral', whoUses: 'Everyone.', when: 'Indifference, or reassuring someone.', examples: [{ nl: 'Thee of koffie? – Maakt niet uit.', en: "Tea or coffee? – Doesn't matter." }], level: 'A2' }),
  e({ id: 'expr.klopt', category: 'reactions', natural: 'Klopt!', textbook: 'Dat is correct.', en: "Right! / That's correct", register: 'neutral', whoUses: 'Everyone.', when: "Agreeing with a fact. 'Correct' sounds like an exam.", examples: [{ nl: 'Je woont in Delft, toch? – Klopt!', en: 'You live in Delft, right? – Right!' }], level: 'A2' }),
  e({ id: 'expr.top', category: 'reactions', natural: 'Top!', textbook: 'Dat is uitstekend.', en: 'Great!', register: 'informal', whoUses: 'Everyone in casual situations.', when: 'Agreeing to a plan or reacting to good news.', examples: [{ nl: 'Morgen om acht uur? – Top!', en: 'Tomorrow at eight? – Great!' }], level: 'A1' }),
  e({ id: 'expr.komt-goed', category: 'reactions', natural: 'Komt goed', textbook: 'Het zal goed komen.', en: "It'll be fine / I'll take care of it", register: 'informal', whoUses: 'Everyone, very common at work too.', when: 'Reassurance — and also a promise to handle something.', examples: [{ nl: 'Stuur je het rapport vandaag? – Komt goed!', en: "Will you send the report today? – Will do!" }], level: 'B1' }),

  // Particles
  e({ id: 'expr.toch', category: 'particles', natural: '…, toch?', textbook: '…, is dat niet zo?', en: '…, right?', register: 'neutral', whoUses: 'Everyone.', when: 'Asking for confirmation when you expect a yes.', examples: [{ nl: 'Jij komt ook, toch?', en: "You're coming too, right?" }], level: 'A2' }),
  e({ id: 'expr.hoor', category: 'particles', natural: '… hoor', en: '(friendly, reassuring tone)', register: 'neutral', whoUses: 'Everyone, especially in the Netherlands.', when: "Softens a statement: 'Dat is goed hoor.'", examples: [{ nl: 'Het is niet erg, hoor.', en: "It's really no problem." }], level: 'A2' }),
  e({ id: 'expr.even', category: 'particles', natural: 'even', en: 'just, quickly', register: 'neutral', whoUses: 'Everyone.', when: 'Makes requests and plans sound light and polite.', examples: [{ nl: 'Mag ik even langs?', en: 'Can I just get past?' }, { nl: 'Ik bel je even terug.', en: "I'll call you back in a sec." }], level: 'A1' }),
  e({ id: 'expr.maar', category: 'particles', natural: 'maar (encouraging)', en: 'go ahead, do', register: 'neutral', whoUses: 'Everyone.', when: "Encourages or gives permission: 'Kom maar binnen.'", examples: [{ nl: 'Pak maar een stoel.', en: 'Go ahead and grab a chair.' }], level: 'A2' }),
  e({ id: 'expr.wel', category: 'particles', natural: 'wel', en: '(does / really — contrast)', register: 'neutral', whoUses: 'Everyone.', when: 'Contrast with a negative or reassurance.', examples: [{ nl: 'Ik heb geen tijd, maar ik kom wel even langs.', en: "I don't have time, but I will stop by briefly." }], level: 'B1' }),
  e({ id: 'expr.gewoon', category: 'particles', natural: 'gewoon', en: 'just, simply', register: 'neutral', whoUses: 'Everyone.', when: "Downplays something: 'Ik doe gewoon mijn best.'", examples: [{ nl: 'Het is gewoon een grapje.', en: "It's just a joke." }], level: 'A2' }),
  e({ id: 'expr.eigenlijk', category: 'particles', natural: 'eigenlijk', en: 'actually', register: 'neutral', whoUses: 'Everyone — one of the most frequent words in speech.', when: 'Softening, correcting or admitting something.', examples: [{ nl: 'Eigenlijk heb ik geen zin.', en: "Actually, I don't feel like it." }], level: 'A2' }),

  // Fillers
  e({ id: 'expr.nou', category: 'fillers', natural: 'Nou…', en: 'Well…', register: 'neutral', whoUses: 'Everyone.', when: 'Starts a reaction — often a hesitation or an objection.', examples: [{ nl: 'Nou, ik weet het niet.', en: "Well, I'm not sure." }], level: 'A2' }),
  e({ id: 'expr.zeg-maar', category: 'fillers', natural: 'zeg maar', en: 'sort of, like', register: 'informal', whoUses: 'Especially younger speakers.', when: 'A filler while you search for words.', examples: [{ nl: 'Het is zeg maar een soort feestje.', en: "It's sort of a kind of party." }], level: 'B1' }),
  e({ id: 'expr.weet-je', category: 'fillers', natural: 'weet je', en: 'you know', register: 'informal', whoUses: 'Everyone in casual speech.', when: 'Keeps the listener with you.', examples: [{ nl: 'Het was, weet je, gewoon raar.', en: 'It was, you know, just weird.' }], level: 'B1' }),
  e({ id: 'expr.even-denken', category: 'fillers', natural: 'Even denken…', textbook: 'Een moment, alstublieft.', en: 'Let me think…', register: 'neutral', whoUses: 'Everyone.', when: 'Buy time without switching to English — the secret weapon of learners.', examples: [{ nl: 'Even denken… ja, dinsdag kan ik.', en: 'Let me think… yes, I can do Tuesday.' }], level: 'A1' }),

  // Social
  e({ id: 'expr.gezellig', category: 'social', natural: 'Gezellig!', en: 'Cosy / lovely / sociable', register: 'neutral', whoUses: 'Everyone — the national word.', when: "Describes a warm atmosphere, company or evening. Also a reply to a plan: 'Gezellig!'", examples: [{ nl: 'Kom je ook? Gezellig!', en: "You're coming too? Lovely!" }, { nl: 'Het was een gezellige avond.', en: 'It was a lovely evening.' }], level: 'A1' }),
  e({ id: 'expr.lekker', category: 'social', natural: 'lekker', en: 'tasty; nice; pleasant', register: 'neutral', whoUses: 'Everyone.', when: 'Food, weather, sleep, activities — anything pleasant.', examples: [{ nl: 'Lekker weer, hè?', en: 'Nice weather, huh?' }, { nl: 'Slaap lekker!', en: 'Sleep well!' }], level: 'A1' }),
  e({ id: 'expr.eet-smakelijk', category: 'social', natural: 'Eet smakelijk!', en: 'Enjoy your meal!', register: 'neutral', whoUses: 'Everyone; in Belgium also just "Smakelijk!"', when: 'Before starting to eat together.', examples: [{ nl: 'Het eten is klaar. Eet smakelijk!', en: 'Dinner is ready. Enjoy!' }], level: 'A1' }),
  e({ id: 'expr.gefeliciteerd-met-je', category: 'social', natural: 'Gefeliciteerd met je …!', en: "Congratulations on your … (relative's birthday)", register: 'neutral', whoUses: 'Everyone at birthday parties.', when: "At a birthday, to the birthday person's partner, parents, children and friends.", examples: [{ nl: 'Gefeliciteerd met je broer!', en: "Congratulations on your brother's birthday!" }], level: 'A2' }),
  e({ id: 'expr.zin-in', category: 'social', natural: 'Ik heb er zin in!', textbook: 'Ik kijk ernaar uit.', en: "I'm looking forward to it!", register: 'neutral', whoUses: 'Everyone.', when: 'Enthusiasm about a plan.', examples: [{ nl: 'Morgen naar het strand? Ik heb er zin in!', en: "Beach tomorrow? I'm looking forward to it!" }], level: 'A2' }),
  e({ id: 'expr.zullen-we', category: 'social', natural: 'Zullen we …?', textbook: 'Wilt u met mij …?', en: 'Shall we …?', register: 'neutral', whoUses: 'Everyone.', when: 'Suggesting a plan.', examples: [{ nl: 'Zullen we een koffietje doen?', en: 'Shall we grab a coffee?' }], level: 'A1' }),

  // Slang
  e({ id: 'expr.chill', category: 'slang', natural: 'chill', en: 'relaxed, nice', register: 'informal', whoUses: 'Teenagers and people under about 35, in the Netherlands and Flanders.', when: 'Casual speech; an English loan.', examples: [{ nl: 'Het was echt chill gisteren.', en: 'It was really chill yesterday.' }], level: 'B1' }),
  e({ id: 'expr.vet', category: 'slang', natural: 'vet', en: 'cool, awesome', register: 'informal', whoUses: 'Young people.', when: "Enthusiasm. (Literally 'fat'.)", examples: [{ nl: 'Dat concert was echt vet!', en: 'That concert was really awesome!' }], region: 'nl', level: 'B1' }),
  e({ id: 'expr.amai', category: 'slang', natural: 'Amai!', en: 'Wow!', register: 'informal', whoUses: 'Flemish speakers of all ages.', when: 'Surprise or admiration.', examples: [{ nl: 'Amai, wat een mooi huis!', en: 'Wow, what a beautiful house!' }], region: 'be', level: 'B1' }),
  e({ id: 'expr.goesting', category: 'slang', natural: 'goesting', textbook: 'zin', en: 'desire, appetite (Flemish)', register: 'informal', whoUses: 'Flemish speakers.', when: "Where Dutch speakers in the Netherlands say 'zin'.", examples: [{ nl: 'Ik heb goesting in frietjes.', en: 'I fancy some fries.' }], region: 'be', level: 'B1' }),
  e({ id: 'expr.appen', category: 'slang', natural: 'Ik app je ff', textbook: 'Ik stuur je een bericht.', en: "I'll text you quickly", register: 'informal', whoUses: 'Everyone who texts.', when: "'Appen' = sending a message through a chat app; 'ff' = even.", examples: [{ nl: 'Ik app je ff als ik er ben.', en: "I'll text you when I'm there." }], level: 'B1' }),

  // Idioms
  e({ id: 'expr.valt-mee', category: 'idioms', natural: 'Het valt mee', en: "It's not as bad as expected", register: 'neutral', whoUses: 'Everyone.', when: "Opposite: 'Het valt tegen' (disappointing).", examples: [{ nl: 'Was het koud? – Het viel mee.', en: "Was it cold? – It wasn't too bad." }], level: 'B1' }),
  e({ id: 'expr.doe-normaal', category: 'idioms', natural: 'Doe normaal!', en: 'Behave! / Come on! / No way!', register: 'informal', whoUses: 'Everyone; tone decides whether it’s a rebuke or a joke.', when: 'Disbelief, teasing or telling someone off.', examples: [{ nl: 'Tien euro voor een koffie? Doe normaal!', en: 'Ten euros for a coffee? Come on!' }], level: 'B2' }),
  e({ id: 'expr.daar-ga-ik-niet-over', category: 'idioms', natural: 'Daar ga ik niet over', en: "That's not my call", register: 'neutral', whoUses: 'Colleagues and officials.', when: 'When the decision belongs to someone else — a very Dutch workplace phrase.', examples: [{ nl: 'Krijg ik een dag extra vrij? – Daar ga ik niet over, vraag het aan Linda.', en: "Can I get an extra day off? – That's not my call, ask Linda." }], level: 'B2' }),
];
