import type { Scenario } from '@praat/core';
import { i } from './helpers.js';

/**
 * Dutch Life Simulator scenarios. Each beat has a communicative goal (intents); the task
 * counts as achieved when the message gets across — grammar is fed back, not gatekept.
 */
export const scenarios: Scenario[] = [
  // ------------------------------------------------------------------ Living
  {
    id: 'living.viewing',
    category: 'living',
    title: 'Viewing an apartment',
    level: 'A2',
    goal: "View the apartment, ask about the costs and availability, and show you're interested.",
    canDoId: 'cd.rent-viewing',
    register: 'formal',
    setting: "You're viewing a two-room apartment in Utrecht. The estate agent (makelaar) opens the door.",
    character: { name: 'Meneer Verhoeven', role: 'Estate agent' },
    goals: ['moving'],
    beats: [
      {
        id: 'greet',
        npc: { nl: 'Goedemiddag! U bent hier voor de bezichtiging?', en: 'Good afternoon! You are here for the viewing?' },
        task: "Greet him, confirm you're here for the viewing and say your name.",
        intents: [i('greet', 'Greet', 'goedemiddag|goedendag|hallo|dag|goedemorgen'), i('confirm', 'Confirm or say your name', 'ja|klopt|bezichtiging|ik ben|ik heet|mijn naam')],
        modelAnswers: ['Goedemiddag! Ja, ik ben Sam Taylor.', 'Goedemiddag, ja, dat klopt. Ik ben Sam Taylor, we hebben gemaild.'],
        hint: 'Goedemiddag! Ja, ik ben …',
        onSuccess: { nl: 'Welkom, komt u binnen.', en: 'Welcome, please come in.' },
        culturalNote: 'Viewings in big cities are short and busy. Be on time and introduce yourself clearly.',
      },
      {
        id: 'rent',
        npc: { nl: 'Dit is de woonkamer, en daar is de slaapkamer. Heeft u vragen?', en: 'This is the living room, and that is the bedroom. Do you have any questions?' },
        task: 'Ask how much the rent is and whether gas, water and electricity are included.',
        intents: [i('rent', 'Ask about the rent', 'huur|kost*|prijs|per maand'), i('included', "Ask what's included", 'inclusief|exclusief|gas|water|licht|energie|servicekosten')],
        modelAnswers: ['Hoeveel is de huur? Is dat inclusief gas, water en licht?', 'Wat kost het per maand, en zijn de servicekosten inclusief?'],
        hint: 'Hoeveel is de huur? Is dat inclusief …?',
        onSuccess: { nl: 'De huur is 1450 euro per maand, exclusief gas, water en licht. Reken op ongeveer 150 euro extra.', en: 'The rent is 1,450 euros a month, excluding gas, water and electricity. Count on about 150 euros extra.' },
        culturalNote: "Rents are often quoted 'kaal' (bare) or 'exclusief'. Always ask what's included — and whether you can register at the address.",
      },
      {
        id: 'available',
        npc: { nl: 'Nog meer vragen?', en: 'Any more questions?' },
        task: 'Ask when the apartment is available.',
        intents: [i('when', 'Ask when it is available', 'wanneer|beschikbaar|vrij|per wanneer|intrekken|verhuizen|erin')],
        modelAnswers: ['Wanneer is het appartement beschikbaar?', 'Per wanneer kan ik erin?'],
        hint: 'Wanneer is het …?',
        onSuccess: { nl: 'Het is per 1 november beschikbaar.', en: 'It is available from 1 November.' },
      },
      {
        id: 'interest',
        npc: { nl: 'En, wat vindt u ervan?', en: 'So, what do you think?' },
        task: "Say you're interested and ask what the next step is.",
        intents: [i('interest', "Say you're interested", 'interesse|geïnteresseerd|mooi|leuk|graag|huren'), i('next', 'Ask about the next step', 'volgende stap|hoe gaat|wat moet ik|verder|documenten|aanmelden|wat nu')],
        modelAnswers: ['Ik heb interesse. Wat is de volgende stap?', 'Ik vind het heel mooi en ik zou het graag huren. Hoe gaat het nu verder?'],
        hint: 'Ik heb interesse. Wat is …?',
        onSuccess: { nl: 'Mooi! Stuurt u mij uw loonstroken en een kopie van uw paspoort, dan hoort u binnen een week van ons.', en: "Great! Send me your payslips and a copy of your passport, and you'll hear from us within a week." },
        culturalNote: "Landlords usually ask for payslips (loonstroken), an employer's statement and ID. Having them ready as PDFs gives you an edge.",
      },
    ],
    debrief:
      'Well done! On the Dutch rental market, speed and completeness win: reply the same day, send all documents at once, keep it short and friendly. Never pay a deposit before you have seen the home and signed a contract — rental scams are common.',
  },
  {
    id: 'living.repair',
    category: 'living',
    title: 'Reporting a repair to your landlord',
    level: 'A2',
    goal: 'Report the broken heating, say since when, and arrange a time for the repair.',
    canDoId: 'cd.repair',
    register: 'formal',
    setting: "It's January and your heating has stopped working. You call your landlord.",
    character: { name: 'Mevrouw De Groot', role: 'Landlord' },
    goals: ['moving'],
    beats: [
      {
        id: 'problem',
        npc: { nl: 'Met De Groot.', en: 'De Groot speaking.' },
        task: "Say who you are (the tenant) and that the heating doesn't work.",
        intents: [i('who', 'Say who you are', 'u spreekt met|met|ik ben|huurder|ik woon|ik heet'), i('problem', 'Say the heating is broken', 'verwarming|cv|ketel|kapot|doet het niet|werkt niet')],
        modelAnswers: ['Goedemiddag, u spreekt met Sam, de huurder van de Kerkstraat 12. De verwarming werkt niet.', 'Hallo mevrouw De Groot, met Sam van de Kerkstraat. Mijn verwarming doet het niet meer.'],
        hint: 'Goedemiddag, u spreekt met … De verwarming …',
        onSuccess: { nl: 'O, vervelend.', en: "Oh, that's annoying." },
        culturalNote: 'In most rental contracts the landlord is responsible for the central-heating boiler (cv-ketel). Report problems quickly — and in writing too.',
      },
      {
        id: 'since',
        npc: { nl: 'Sinds wanneer is dat?', en: 'Since when?' },
        task: "Say since when it's been broken and that it's very cold.",
        intents: [i('since', 'Say since when', 'sinds|gisteren|vanochtend|eergisteren|dagen|al')],
        modelAnswers: ['Sinds gisteren. Het is erg koud in huis.', 'Al sinds zaterdag. We hebben het echt koud.'],
        hint: 'Sinds gisteren. Het is …',
        onSuccess: { nl: 'Dat is niet goed. Ik stuur een monteur.', en: "That's not good. I'll send a mechanic." },
      },
      {
        id: 'time',
        npc: { nl: 'Kan de monteur morgen tussen acht en twaalf komen?', en: 'Can the mechanic come tomorrow between eight and twelve?' },
        task: "You work in the morning. Say that doesn't suit you and propose the afternoon.",
        intents: [i('decline', "Say the morning doesn't work", 'kan niet|kan ik niet|lukt niet|werk*|helaas|komt niet'), i('alt', 'Propose another time', 'middag*|na twaalf|na de lunch|later|uur|#num')],
        modelAnswers: ["Helaas, dan moet ik werken. Kan het ook 's middags?", 'Morgenochtend kan ik niet. Kan hij na twaalf uur komen?'],
        hint: "Helaas, dan … Kan het ook 's middags?",
        onSuccess: { nl: 'Prima, dan komt hij tussen één en vijf.', en: "Fine, then he'll come between one and five." },
      },
      {
        id: 'close',
        npc: { nl: 'Is er verder nog iets?', en: 'Is there anything else?' },
        task: 'Thank her and end the call.',
        intents: [i('thanks', 'Thank her', 'dank|bedankt'), i('bye', 'Close the call', 'tot ziens|dag|fijne dag|tot horens|prettige dag|dat was het|dat is alles')],
        modelAnswers: ['Nee, dat was het. Dank u wel, tot ziens!', 'Dank u wel voor de snelle hulp. Fijne dag!'],
        hint: 'Dank u wel, …',
      },
    ],
    debrief:
      "Nice work. Follow up with a short email ('Zoals besproken…' — as discussed) so there's a written record. If a landlord doesn't fix serious defects, tenants in the Netherlands can turn to the Huurcommissie (rent tribunal).",
  },
  {
    id: 'living.gemeente',
    category: 'living',
    title: 'Registering at the town hall',
    level: 'A2',
    goal: 'Explain why you are there, hand over your documents and answer questions.',
    canDoId: 'cd.gemeente',
    register: 'formal',
    setting: 'You have an appointment at the town hall (gemeentehuis) to register your new address.',
    character: { name: 'Mevrouw Jansen', role: 'Civil servant' },
    goals: ['moving'],
    beats: [
      {
        id: 'why',
        npc: { nl: 'Goedemorgen. Waarvoor komt u?', en: 'Good morning. What have you come for?' },
        task: 'Say you want to register at your new address.',
        intents: [i('register', 'Say you want to register', 'inschrijven|inschrijving|registreren|aanmelden|adres|verhuisd')],
        modelAnswers: ['Goedemorgen. Ik wil me graag inschrijven op mijn nieuwe adres.', 'Ik ben net verhuisd en ik wil mijn adres registreren.'],
        hint: 'Ik wil me graag inschrijven …',
        onSuccess: { nl: 'Prima.', en: 'Fine.' },
        culturalNote: 'Everyone who will live in the Netherlands for more than four months must register with the municipality. First-time registration gives you a citizen service number (BSN).',
      },
      {
        id: 'documents',
        npc: { nl: 'Mag ik uw paspoort en uw huurcontract zien?', en: 'May I see your passport and your rental contract?' },
        task: 'Hand over the documents politely.',
        intents: [i('give', 'Hand them over', 'alstublieft|alsjeblieft|hier|natuurlijk|ja')],
        modelAnswers: ['Ja, natuurlijk. Alstublieft.', 'Hier zijn mijn paspoort en mijn huurcontract.'],
        hint: 'Ja, natuurlijk. Alst…',
        onSuccess: { nl: 'Dank u wel.', en: 'Thank you.' },
      },
      {
        id: 'date',
        npc: { nl: 'Sinds wanneer woont u op dit adres?', en: 'Since when have you lived at this address?' },
        task: 'Say since when you have lived there.',
        intents: [i('date', 'Give a date', 'sinds|januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december|#num|vorige week|gisteren')],
        modelAnswers: ['Sinds 1 oktober.', 'Ik woon er sinds vorige week, sinds 15 september.'],
        hint: 'Sinds …',
        onSuccess: { nl: 'Goed, dan is alles compleet.', en: 'Good, then everything is complete.' },
      },
      {
        id: 'bsn',
        npc: { nl: 'Uw BSN ontvangt u binnen een week per post. Heeft u nog vragen?', en: 'You will receive your BSN by post within a week. Any questions?' },
        task: "Ask whether you need to do anything else, or say no and thank her.",
        intents: [i('close', 'Ask a question or thank her', 'dank|bedankt|moet ik|nog iets|vraag')],
        modelAnswers: ['Nee, dank u wel. Fijne dag!', 'Moet ik verder nog iets doen?'],
        hint: 'Nee, dank u wel …',
      },
    ],
    debrief:
      'Done! Your registration unlocks almost everything: a BSN, a bank account, health insurance, a GP. Always bring original documents; foreign birth certificates may need an apostille and a sworn translation.',
  },
  {
    id: 'living.letter',
    category: 'living',
    title: 'Calling about an official letter',
    level: 'B1',
    goal: 'Explain the letter, find out what it means and what (if anything) you need to do.',
    canDoId: 'cd.letters',
    register: 'formal',
    setting: "You received a letter about your healthcare allowance (zorgtoeslag) that you don't understand. You call the helpdesk.",
    character: { name: 'Medewerker', role: 'Helpdesk advisor' },
    goals: ['moving', 'work'],
    beats: [
      {
        id: 'explain',
        npc: { nl: 'Goedemiddag, u spreekt met de helpdesk toeslagen. Waarmee kan ik u helpen?', en: 'Good afternoon, this is the allowances helpdesk. How can I help you?' },
        task: "Say you got a letter about your healthcare allowance and that you don't understand it.",
        intents: [i('letter', 'Mention the letter', 'brief|bericht|post'), i('topic', 'Say what it is about', 'zorgtoeslag|toeslag'), i('understand', "Say you don't understand", 'begrijp|snap|niet duidelijk|onduidelijk')],
        modelAnswers: ['Goedemiddag. Ik heb een brief gekregen over mijn zorgtoeslag, maar ik begrijp hem niet.', 'Ik heb een brief ontvangen over de zorgtoeslag en het is mij niet duidelijk wat ik moet doen.'],
        hint: 'Ik heb een brief gekregen over … maar ik begrijp …',
        onSuccess: { nl: 'Ik help u graag.', en: "I'm happy to help." },
      },
      {
        id: 'bsn',
        npc: { nl: 'Mag ik uw burgerservicenummer?', en: 'May I have your citizen service number?' },
        task: 'Give your BSN (make up nine digits).',
        intents: [i('number', 'Give a number', '#num')],
        modelAnswers: ['Ja, dat is 123456782.', 'Mijn BSN is 1234 56 782.'],
        hint: 'Mijn BSN is …',
        onSuccess: { nl: 'Dank u. Ik zie het al: uw toeslag wordt verlaagd, omdat uw inkomen hoger is dan verwacht.', en: 'Thank you. I can see it: your allowance is being reduced because your income is higher than expected.' },
      },
      {
        id: 'what-do',
        npc: { nl: 'Klopt het dat u meer bent gaan verdienen?', en: 'Is it correct that you started earning more?' },
        task: 'Confirm (you have a new job) and ask what you need to do.',
        intents: [i('confirm', 'Confirm', 'ja|klopt|nieuwe baan'), i('ask', 'Ask what to do', 'wat moet ik|moet ik|wat kan ik|hoe')],
        modelAnswers: ['Ja, dat klopt, ik heb een nieuwe baan. Wat moet ik nu doen?', 'Klopt. Moet ik iets doorgeven?'],
        hint: 'Ja, dat klopt. Wat moet ik …?',
        onSuccess: { nl: 'U hoeft niets te doen. Maar let op: als uw inkomen verandert, geeft u dat zelf door via de website.', en: "You don't need to do anything. But note: if your income changes, you report it yourself via the website." },
      },
      {
        id: 'close',
        npc: { nl: 'Heeft u verder nog vragen?', en: 'Do you have any other questions?' },
        task: "Thank them (and, if you like, ask whether you'll get a new letter).",
        intents: [i('thanks', 'Thank them', 'dank|bedankt')],
        modelAnswers: ['Krijg ik nog een nieuwe brief? En dank u wel voor de uitleg.', 'Nee, dat was het. Heel erg bedankt voor de hulp!'],
        hint: 'Dank u wel voor …',
      },
    ],
    debrief:
      "You handled officialese on the phone. Dutch agencies work mostly in writing and online (with DigiD). Note the date, who you spoke to and what was agreed. If a letter mentions 'bezwaar maken', you can formally object — there's always a deadline, usually six weeks.",
  },

  // ------------------------------------------------------------------ Social
  {
    id: 'social.first-meeting',
    category: 'social',
    title: "Meeting a friend's friends",
    level: 'A1',
    goal: "Introduce yourself, say where you're from and what you do, and ask something back.",
    canDoId: 'cd.introduce',
    register: 'informal',
    setting: "Your friend Joost takes you to a café where his friends are. Lotte sits next to you.",
    character: { name: 'Lotte', role: "A friend of your friend" },
    goals: ['partner', 'study', 'culture', 'moving'],
    beats: [
      {
        id: 'name',
        npc: { nl: 'Hoi! Ik ben Lotte. Jij bent de vriend van Joost, toch?', en: "Hi! I'm Lotte. You're Joost's friend, right?" },
        task: 'Say hi and your name.',
        intents: [i('greet', 'Greet', 'hoi|hallo|hey|he|hee|ja'), i('name', 'Say your name', 'ik ben|ik heet|heet')],
        modelAnswers: ['Hoi! Ja, ik ben Sam.', 'Hé Lotte, leuk je te ontmoeten! Ik heet Sam.'],
        hint: 'Hoi! Ik ben …',
        onSuccess: { nl: 'Leuk!', en: 'Nice!' },
      },
      {
        id: 'origin',
        npc: { nl: 'Waar kom je vandaan?', en: 'Where are you from?' },
        task: "Say where you're from and where you live now.",
        intents: [i('from', "Say where you're from", 'uit|vandaan'), i('live', 'Say where you live', 'woon*|wonen')],
        modelAnswers: ['Ik kom uit Canada, maar ik woon nu in Utrecht.', 'Uit Brazilië. Ik woon sinds januari in Amsterdam.'],
        hint: 'Ik kom uit … en ik woon …',
        onSuccess: { nl: 'O, cool!', en: 'Oh, cool!' },
      },
      {
        id: 'work',
        npc: { nl: 'En wat doe je hier? Werk je, of studeer je?', en: 'And what do you do here? Do you work, or study?' },
        task: 'Say what you do.',
        intents: [i('job', 'Say what you do', 'werk|studeer|ben|doe')],
        modelAnswers: ['Ik werk als verpleegkundige.', 'Ik studeer psychologie aan de universiteit.'],
        hint: 'Ik werk als … / Ik studeer …',
        onSuccess: { nl: 'Wat leuk!', en: 'How nice!' },
      },
      {
        id: 'ask',
        npc: { nl: 'Vind je het leuk hier?', en: 'Do you like it here?' },
        task: 'Answer, then ask Lotte a question back.',
        intents: [i('answer', 'Answer', 'ja|leuk|gezellig|mooi|nee|best'), i('question', 'Ask her a question', 'en jij|wat doe jij|wat doe je|waar woon|hoe ken')],
        modelAnswers: ['Ja, heel leuk! En jij, wat doe jij?', 'Ja, het is hier gezellig. Hoe ken jij Joost?'],
        hint: 'Ja! En jij, …?',
        onSuccess: { nl: 'Ik ben lerares. Joost en ik kennen elkaar van de hockeyclub.', en: "I'm a teacher. Joost and I know each other from the hockey club." },
      },
    ],
    debrief:
      "Nice first meeting! Dutch conversations move quickly from name to job — 'Wat doe je?' is a standard early question. Asking questions back keeps things going; genuine curiosity is appreciated more than compliments.",
  },
  {
    id: 'social.birthday',
    category: 'social',
    title: 'At a birthday party',
    level: 'A2',
    goal: 'Congratulate the host and her family, say how you know her and join the chat.',
    canDoId: 'cd.birthday',
    register: 'neutral',
    setting: "Your colleague Anouk's 30th birthday at her apartment. Family and friends sit in a circle.",
    character: { name: 'Anouk', role: 'Colleague celebrating her birthday' },
    goals: ['partner', 'work', 'moving', 'culture'],
    beats: [
      {
        id: 'congrats',
        npc: { nl: 'Hé, je bent er! Kom binnen!', en: 'Hey, you made it! Come in!' },
        task: 'Congratulate Anouk and give her a present.',
        intents: [i('congrats', 'Congratulate', 'gefeliciteerd|proficiat|van harte')],
        modelAnswers: ['Gefeliciteerd, Anouk! Hier is een cadeautje.', 'Hoi! Van harte gefeliciteerd! Dit is voor jou.'],
        hint: 'Gefeliciteerd! Hier is …',
        onSuccess: { nl: 'O, wat lief! Dank je wel.', en: 'Oh, how sweet! Thank you.' },
      },
      {
        id: 'family',
        npc: { nl: 'Hallo, ik ben Ellen, de moeder van Anouk.', en: "Hello, I'm Ellen, Anouk's mother." },
        task: 'Greet her the Dutch way: congratulate her on her daughter.',
        intents: [i('congrats', 'Congratulate her on her daughter', 'gefeliciteerd|proficiat|van harte')],
        modelAnswers: ['Hallo, gefeliciteerd met uw dochter!', 'Dag mevrouw, gefeliciteerd met Anouk!'],
        hint: 'Gefeliciteerd met …',
        onSuccess: { nl: 'Dank je wel!', en: 'Thank you!' },
        culturalNote: "At a Dutch birthday you congratulate the whole family: 'Gefeliciteerd met je dochter / vriend / zus!'",
      },
      {
        id: 'how',
        npc: { nl: 'Hoe ken jij Anouk eigenlijk?', en: 'How do you know Anouk, actually?' },
        task: 'Explain how you know Anouk.',
        intents: [i('how', 'Explain how you know her', 'collega*|werk|ken|vriend*|buur*|sport*|school|studie|via')],
        modelAnswers: ["We zijn collega's.", 'Ik ken haar van het werk. We zitten in hetzelfde team.'],
        hint: 'Ik ken haar van …',
        onSuccess: { nl: 'O, leuk!', en: 'Oh, nice!' },
      },
      {
        id: 'offer',
        npc: { nl: 'Wil je koffie en een stukje taart?', en: 'Would you like coffee and a piece of cake?' },
        task: 'Accept politely.',
        intents: [i('accept', 'Accept', 'graag|ja|lekker|dank')],
        modelAnswers: ['Ja, graag!', 'Lekker, graag! Dank je wel.'],
        hint: 'Ja, …',
      },
    ],
    debrief:
      'Gefeliciteerd — you survived the circle! The classic order: coffee and cake first, drinks and snacks later. When you leave, say goodbye to everyone, not just the host.',
  },
  {
    id: 'social.neighbour',
    category: 'social',
    title: 'Small talk with a neighbour',
    level: 'A2',
    goal: 'Chat about the weather and your weekend, and offer help.',
    canDoId: 'cd.small-talk',
    register: 'neutral',
    setting: 'Saturday morning. Your elderly neighbour is in his front garden as you come out.',
    character: { name: 'Meneer Pieters', role: 'Your neighbour' },
    goals: ['moving', 'culture'],
    beats: [
      {
        id: 'weather',
        npc: { nl: 'Goedemorgen! Mooi weer vandaag, hè?', en: "Good morning! Lovely weather today, isn't it?" },
        task: 'Greet him and agree about the weather.',
        intents: [i('greet', 'Greet', 'goedemorgen|hallo|hoi|dag'), i('agree', 'React to the weather', 'ja|mooi|heerlijk|lekker|zeker|eindelijk|klopt')],
        modelAnswers: ['Goedemorgen! Ja, heerlijk!', 'Goedemorgen, meneer Pieters. Ja, eindelijk zon!'],
        hint: 'Goedemorgen! Ja, …',
        onSuccess: { nl: 'Zeker.', en: 'Absolutely.' },
      },
      {
        id: 'plans',
        npc: { nl: 'Nog plannen voor het weekend?', en: 'Any plans for the weekend?' },
        task: "Tell him one thing you're going to do this weekend.",
        intents: [i('plan', "Say what you're going to do", 'ga|gaan|ben van plan|wil')],
        modelAnswers: ['Ja, ik ga naar de markt en ik ga fietsen.', 'We gaan morgen naar het strand.'],
        hint: 'Ja, ik ga …',
        onSuccess: { nl: 'Leuk, geniet ervan!', en: 'Nice, enjoy it!' },
      },
      {
        id: 'help',
        npc: { nl: 'Ik moet straks die zware zakken tuinaarde naar achteren brengen. Mijn rug, hè…', en: 'Later I have to carry those heavy bags of soil to the back. My back, you know…' },
        task: 'Offer to help him.',
        intents: [i('offer', 'Offer help', 'help*|zal ik|kan ik|zullen we|samen')],
        modelAnswers: ['Zal ik u even helpen?', 'Ik help u wel even, hoor!'],
        hint: 'Zal ik u even …?',
        onSuccess: { nl: 'Wat aardig van je! Dank je wel.', en: 'How kind of you! Thank you.' },
        culturalNote: "Neighbourly help is appreciated, but people also value independence — offer once and accept a 'nee hoor' without insisting.",
      },
    ],
    debrief:
      "Great chat! Good neighbours matter in Dutch culture: 'Beter een goede buur dan een verre vriend' — better a good neighbour than a distant friend.",
  },
  {
    id: 'social.borrel',
    category: 'social',
    title: 'Joining the conversation at a borrel',
    level: 'B1',
    goal: 'Jump in politely, give your opinion with a reason, and ask the group a follow-up question.',
    canDoId: 'cd.group',
    register: 'informal',
    setting: 'Friday drinks. Three colleagues are discussing whether the office should switch to a four-day week.',
    character: { name: 'Pieter', role: 'Colleague' },
    goals: ['work', 'study'],
    beats: [
      {
        id: 'jump',
        npc: { nl: '…dus ik zeg: vier dagen werken, vijf dagen betaald. Toch?', en: '…so I say: work four days, get paid for five. Right?' },
        task: 'Jump into the conversation politely.',
        intents: [i('jump', 'Jump in', 'mag ik|even|wacht|sorry|trouwens|nou|interessant')],
        modelAnswers: ['Mag ik even wat zeggen?', 'Interessant! Mag ik ook iets zeggen?'],
        hint: 'Mag ik even …?',
        onSuccess: { nl: 'Tuurlijk, zeg het maar!', en: 'Of course, go ahead!' },
      },
      {
        id: 'opinion',
        npc: { nl: 'Wat vind jij ervan?', en: 'What do you think?' },
        task: 'Give your opinion and a reason.',
        intents: [i('opinion', 'Give your opinion', 'vind|volgens mij|denk|eens|mening'), i('reason', 'Give a reason', 'omdat|want|dus|daarom')],
        modelAnswers: ['Ik vind het een goed idee, want mensen zijn dan minder moe.', 'Volgens mij werkt het niet voor iedereen, omdat klanten ons vijf dagen nodig hebben.'],
        hint: 'Ik vind … want …',
        onSuccess: { nl: 'Hm, goed punt.', en: 'Hm, good point.' },
      },
      {
        id: 'follow-up',
        npc: { nl: 'Ja, daar zit wat in. Maar hoe zou jij dat dan regelen?', en: "Yes, there's something in that. But how would you arrange it, then?" },
        task: 'Suggest something and ask the others a question.',
        intents: [i('suggest', 'Suggest something', 'misschien|ik zou|zullen we|we kunnen|stel voor|wat als'), i('ask', 'Ask the group', 'jullie|wat denken|wat vinden|of niet')],
        modelAnswers: ['Misschien kunnen we eerst een proef doen. Wat vinden jullie?', 'Ik zou het per team regelen. Hoe doen jullie dat nu?'],
        hint: 'Misschien kunnen we … Wat vinden jullie?',
        onSuccess: { nl: 'Dat is eigenlijk best slim!', en: "That's actually quite smart!" },
      },
    ],
    debrief:
      "You held your own in a fast group discussion! Dutch colleagues respect clear opinions with reasons — even disagreement — and 'Mag ik even…' is the perfect way in.",
  },

  // ------------------------------------------------------------------ Daily life
  {
    id: 'daily.supermarket',
    category: 'daily',
    title: 'At the supermarket',
    level: 'A1',
    goal: 'Find the peanut butter, then pay at the checkout.',
    canDoId: 'cd.shop',
    register: 'neutral',
    setting: 'A busy supermarket on a Saturday.',
    character: { name: 'Daan', role: 'Supermarket employee' },
    goals: ['moving', 'travel', 'study'],
    beats: [
      {
        id: 'where',
        npc: { nl: 'Kan ik je ergens mee helpen?', en: 'Can I help you with anything?' },
        task: 'Ask where the peanut butter (pindakaas) is.',
        intents: [i('where', 'Ask where it is', 'waar'), i('item', 'Mention peanut butter', 'pindakaas')],
        modelAnswers: ['Ja, waar is de pindakaas?', 'Ja graag, waar kan ik de pindakaas vinden?'],
        hint: 'Waar is de …?',
        onSuccess: { nl: 'Die staat in gang drie, bij het ontbijt.', en: "It's in aisle three, with the breakfast items." },
      },
      {
        id: 'bag',
        npc: { nl: 'Goedemiddag. Heb je een tasje nodig?', en: 'Good afternoon. Do you need a bag?' },
        task: "Say no, you've brought your own bag.",
        intents: [i('no', 'Decline', 'nee|hoeft niet|geen|tas bij|eigen tas')],
        modelAnswers: ['Nee, dank je, ik heb een tas bij me.', 'Hoeft niet, dank je!'],
        hint: 'Nee, dank je, ik heb …',
        onSuccess: { nl: 'Top.', en: 'Great.' },
      },
      {
        id: 'pay',
        npc: { nl: 'Dat is dan elf euro vijfenveertig. Pinnen?', en: "That's eleven euros forty-five. Paying by card?" },
        task: 'Say yes, you want to pay by card.',
        intents: [i('yes', 'Confirm paying by card', 'ja|pinnen|pin|kaart|graag')],
        modelAnswers: ['Ja, pinnen graag.', 'Ja, met de kaart.'],
        hint: 'Ja, …',
      },
      {
        id: 'receipt',
        npc: { nl: 'Wil je de bon?', en: 'Do you want the receipt?' },
        task: "Say you don't need it, and say goodbye.",
        intents: [i('no', 'Decline the receipt', 'nee|hoeft niet|niet nodig'), i('bye', 'Say goodbye', 'doei|dag|fijne dag|tot ziens|dank')],
        modelAnswers: ['Nee, hoeft niet. Dank je, doei!', 'Nee, dank je. Fijne dag!'],
        hint: 'Nee, hoeft niet …',
      },
    ],
    debrief:
      "Smooth! Supermarkets are perfect for daily micro-practice: short, predictable exchanges. In the Netherlands cashiers usually say 'je' to customers of all ages.",
  },
  {
    id: 'daily.cafe',
    category: 'daily',
    title: 'Ordering at a café',
    level: 'A1',
    goal: 'Order a drink and something to eat, and pay.',
    canDoId: 'cd.order',
    register: 'neutral',
    setting: 'A cosy café in Groningen.',
    character: { name: 'Joris', role: 'Barista' },
    goals: ['travel', 'culture', 'study'],
    beats: [
      {
        id: 'drink',
        npc: { nl: 'Hoi! Wat mag het zijn?', en: 'Hi! What will it be?' },
        task: 'Order a drink.',
        intents: [i('drink', 'Order a drink', 'koffie|cappuccino|latte|thee|water|cola|biertje|bier|wijn|chocomel|sap|jus')],
        modelAnswers: ['Een cappuccino, alsjeblieft.', 'Mag ik een thee?'],
        hint: 'Een …, alsjeblieft.',
        onSuccess: { nl: 'Komt eraan!', en: 'Coming right up!' },
      },
      {
        id: 'food',
        npc: { nl: 'Wil je er iets bij? We hebben appeltaart.', en: 'Would you like something with it? We have apple pie.' },
        task: 'Order the apple pie — with whipped cream (slagroom).',
        intents: [i('yes', 'Say yes', 'ja|graag|lekker|doe maar'), i('cream', 'Ask for cream', 'slagroom')],
        modelAnswers: ['Ja, lekker! Met slagroom, graag.', 'Doe maar een stuk appeltaart met slagroom.'],
        hint: 'Ja, met …',
        onSuccess: { nl: 'Goede keuze.', en: 'Good choice.' },
        culturalNote: "'Appeltaart met slagroom' is a Dutch café classic. 'Doe maar…' is a very natural way to order.",
      },
      {
        id: 'pay',
        npc: { nl: 'Dat wordt dan zeven euro twintig.', en: "That'll be seven euros twenty." },
        task: 'Ask if you can pay by card.',
        intents: [i('card', 'Ask to pay by card', 'pinnen|pin|kaart|betalen')],
        modelAnswers: ['Kan ik pinnen?', 'Kan ik met de kaart betalen?'],
        hint: 'Kan ik …?',
      },
    ],
    debrief:
      "Lekker! Café Dutch is short: 'Een cappuccino, graag.' – 'Komt eraan.' Politeness lives in 'graag', 'alsjeblieft' and a smile, not in long sentences.",
  },
  {
    id: 'daily.pharmacy',
    category: 'daily',
    title: 'At the pharmacy',
    level: 'A2',
    goal: 'Describe your symptoms, answer questions and understand how to take the medicine.',
    canDoId: 'cd.pharmacy',
    register: 'formal',
    setting: 'The pharmacy (apotheek). You have a cold and a sore throat.',
    character: { name: 'Mevrouw Visser', role: 'Pharmacy assistant' },
    goals: ['moving', 'travel'],
    beats: [
      {
        id: 'symptoms',
        npc: { nl: 'Goedemiddag, zegt u het maar.', en: 'Good afternoon, how can I help?' },
        task: 'Say you have a sore throat and a cold, and ask for something for it.',
        intents: [i('symptom', 'Describe your symptoms', 'keelpijn|verkouden|hoest*|pijn|koorts|neus'), i('ask', 'Ask for something', 'iets|middel|tegen|heeft u')],
        modelAnswers: ['Goedemiddag. Ik heb keelpijn en ik ben verkouden. Heeft u daar iets voor?', 'Ik ben erg verkouden en ik heb pijn in mijn keel. Heeft u iets tegen keelpijn?'],
        hint: 'Ik heb … Heeft u daar iets voor?',
        onSuccess: { nl: 'Dat is vervelend.', en: "That's unpleasant." },
      },
      {
        id: 'allergy',
        npc: { nl: 'Bent u ergens allergisch voor, of gebruikt u andere medicijnen?', en: 'Are you allergic to anything, or do you take any other medication?' },
        task: "Say you're not allergic and don't take other medicine.",
        intents: [i('answer', 'Answer', 'nee|niet|geen|ja')],
        modelAnswers: ['Nee, ik ben nergens allergisch voor en ik gebruik geen medicijnen.', 'Nee, niet dat ik weet.'],
        hint: 'Nee, ik ben nergens …',
        onSuccess: { nl: 'Dan geef ik u deze zuigtabletten en een neusspray.', en: "Then I'll give you these lozenges and a nasal spray." },
      },
      {
        id: 'dosage',
        npc: { nl: 'Heeft u vragen over het gebruik?', en: 'Do you have any questions about how to use them?' },
        task: 'Ask how often you should take them.',
        intents: [i('howoften', 'Ask how often', 'hoe vaak|hoeveel|per dag|keer|wanneer|hoe lang')],
        modelAnswers: ['Hoe vaak moet ik ze nemen?', 'Hoeveel keer per dag mag ik de spray gebruiken?'],
        hint: 'Hoe vaak moet ik …?',
        onSuccess: { nl: 'Maximaal zes tabletten per dag, en de neusspray drie keer per dag, niet langer dan een week.', en: 'Up to six lozenges a day, and the nasal spray three times a day, for no longer than a week.' },
        culturalNote: 'For simple complaints you can also go to a drogist, which sells non-prescription medicine. The apotheek handles prescriptions (recepten) and gives expert advice.',
      },
      {
        id: 'check',
        npc: { nl: 'Is dat duidelijk?', en: 'Is that clear?' },
        task: 'Briefly repeat the instructions to check, and thank her.',
        intents: [i('repeat', 'Repeat the instructions', 'zes|drie|week|per dag'), i('thanks', 'Thank her', 'dank|bedankt')],
        modelAnswers: ['Dus zes tabletten per dag en de spray drie keer per dag, maximaal een week. Dank u wel!', 'Oké, drie keer per dag de spray. Dank u!'],
        hint: 'Dus … per dag. Dank u wel!',
      },
    ],
    debrief:
      "Well done — checking instructions by repeating them ('Dus…') is a great habit, and very Dutch. Pharmacists are highly trained and happy to advise, so don't hesitate to ask.",
  },
  {
    id: 'daily.restaurant',
    category: 'daily',
    title: 'Dinner at a restaurant',
    level: 'A2',
    goal: 'Check in with your reservation, order, handle a small problem and pay.',
    canDoId: 'cd.restaurant',
    register: 'neutral',
    setting: "You arrive at a restaurant in 's-Hertogenbosch. You've reserved a table.",
    character: { name: 'Kim', role: 'Waiter' },
    goals: ['travel', 'culture', 'partner'],
    beats: [
      {
        id: 'reservation',
        npc: { nl: 'Goedenavond! Heeft u gereserveerd?', en: 'Good evening! Do you have a reservation?' },
        task: 'Say you have a reservation for two, under your name.',
        intents: [i('res', 'Mention the reservation', 'gereserveerd|reservering|reserveren'), i('detail', 'Give your name or number of people', 'naam|twee|drie|vier|personen|#num')],
        modelAnswers: ['Goedenavond, ja, we hebben gereserveerd voor twee personen, op naam van Taylor.', 'Ja, we hebben een reservering voor twee, op naam van Taylor.'],
        hint: 'Ja, op naam van …',
        onSuccess: { nl: 'Loopt u maar mee.', en: 'Please follow me.' },
      },
      {
        id: 'order',
        npc: { nl: 'Wat mag ik voor u noteren?', en: 'What can I get you?' },
        task: 'Order a main course and a drink.',
        intents: [i('order', 'Order', 'neem|graag|mag ik|ik wil|voor mij')],
        modelAnswers: ['Ik neem de vis van de dag en een glas witte wijn.', 'Voor mij de stamppot, graag. En een biertje.'],
        hint: 'Ik neem …',
        onSuccess: { nl: 'Prima.', en: 'Very well.' },
      },
      {
        id: 'problem',
        npc: { nl: 'Smaakt het?', en: 'Is everything to your liking?' },
        task: 'Politely say your dish is cold.',
        intents: [i('problem', 'Say the food is cold', 'koud|lauw|niet warm')],
        modelAnswers: ['Het is lekker, maar mijn eten is een beetje koud.', 'Eerlijk gezegd is mijn vis helaas koud.'],
        hint: 'Eerlijk gezegd is mijn … koud.',
        onSuccess: { nl: 'O, excuses! Ik laat het meteen opwarmen.', en: "Oh, apologies! I'll have it warmed up right away." },
        culturalNote: 'Being direct about a problem is normal and expected — say it calmly and staff will usually fix it right away.',
      },
      {
        id: 'bill',
        npc: { nl: 'Kan ik nog iets voor u doen?', en: 'Can I get you anything else?' },
        task: 'Ask for the bill.',
        intents: [i('bill', 'Ask for the bill', 'afrekenen|rekening|betalen')],
        modelAnswers: ['Nee, dank u. Mogen we afrekenen?', 'Mag ik de rekening, alstublieft?'],
        hint: 'Mogen we …?',
      },
    ],
    debrief:
      'Nice evening! Service is included in Dutch prices; rounding up or leaving 5–10% for good service is appreciated but not obligatory. Splitting the bill is common and nobody finds it rude.',
  },
  {
    id: 'daily.station',
    category: 'daily',
    title: 'At the train station',
    level: 'A2',
    goal: 'Find your train, ask about the delay and decide what to do.',
    canDoId: 'cd.train',
    register: 'neutral',
    setting: 'Utrecht Centraal. You need to get to Zwolle, but the departure board shows a delay.',
    character: { name: 'Ruud', role: 'Station staff' },
    goals: ['travel', 'moving', 'work'],
    beats: [
      {
        id: 'which',
        npc: { nl: 'Goedemiddag, kan ik u helpen?', en: 'Good afternoon, can I help you?' },
        task: 'Ask which train goes to Zwolle.',
        intents: [i('which', 'Ask which train or platform', 'welke trein|welk spoor|hoe kom ik|trein naar|waar vertrekt'), i('dest', 'Mention Zwolle', 'zwolle')],
        modelAnswers: ['Ja, graag. Welke trein gaat naar Zwolle?', 'Hoe kom ik naar Zwolle?'],
        hint: 'Welke trein gaat naar …?',
        onSuccess: { nl: 'De intercity van acht over twee, vanaf spoor achttien.', en: 'The 2:08 intercity, from platform eighteen.' },
      },
      {
        id: 'delay',
        npc: { nl: 'Maar die heeft vandaag helaas een kwartier vertraging.', en: 'But unfortunately it has a fifteen-minute delay today.' },
        task: 'Ask if there is another option.',
        intents: [i('other', 'Ask about another option', 'ander*|sneller|alternatief|overstappen|bus')],
        modelAnswers: ['Is er een andere trein?', 'Kan ik ook op een andere manier gaan, bijvoorbeeld met overstappen?'],
        hint: 'Is er een andere …?',
        onSuccess: { nl: 'U kunt de sprinter naar Amersfoort nemen en daar overstappen. Dan bent u er ongeveer even laat.', en: "You can take the local train to Amersfoort and change there. Then you'll arrive at about the same time." },
      },
      {
        id: 'decide',
        npc: { nl: 'Wat wilt u doen?', en: 'What would you like to do?' },
        task: "Say what you'll do and thank him.",
        intents: [i('decide', 'Say what you will do', 'wacht|neem|intercity|sprinter|ga'), i('thanks', 'Thank him', 'dank|bedankt')],
        modelAnswers: ['Dan wacht ik op de intercity. Dank u wel!', 'Ik neem de sprinter. Bedankt voor de hulp!'],
        hint: 'Dan wacht ik … Dank u wel!',
      },
    ],
    debrief:
      "Good travelling! Big stations announce in Dutch and English, but smaller ones often only in Dutch — so 'vertraging', 'spoorwijziging' (platform change) and 'overstappen' are key words.",
  },
  {
    id: 'daily.gp',
    category: 'daily',
    title: 'Calling the GP',
    level: 'A2',
    goal: 'Get an appointment: explain the problem, answer the triage questions and agree on a time.',
    canDoId: 'cd.gp',
    register: 'formal',
    setting: "You call your GP practice. You've had a bad cough for two weeks.",
    character: { name: 'Sandra', role: "GP's assistant" },
    goals: ['moving', 'work', 'study'],
    beats: [
      {
        id: 'intro',
        npc: { nl: 'Huisartsenpraktijk De Linde, met Sandra.', en: 'De Linde GP practice, Sandra speaking.' },
        task: 'Say your name and that you want an appointment.',
        intents: [i('name', 'Say your name', 'u spreekt met|met|ik ben|mijn naam|ik heet'), i('appointment', 'Ask for an appointment', 'afspraak')],
        modelAnswers: ['Goedemorgen, u spreekt met Sam Taylor. Ik wil graag een afspraak maken.', 'Goedemorgen, met Sam Taylor. Kan ik een afspraak maken bij de huisarts?'],
        hint: 'Goedemorgen, u spreekt met … Ik wil graag een afspraak …',
        onSuccess: { nl: 'Natuurlijk.', en: 'Of course.' },
      },
      {
        id: 'symptoms',
        npc: { nl: 'Wat zijn uw klachten?', en: 'What are your symptoms?' },
        task: "Describe your problem and say how long you've had it.",
        intents: [i('symptom', 'Describe the problem', 'hoest*|pijn|koorts|benauwd|verkouden|keel'), i('duration', 'Say how long', 'weken|dagen|week|sinds|al')],
        modelAnswers: ['Ik hoest al twee weken en ik ben erg moe.', 'Ik heb al twee weken een hoest die niet overgaat.'],
        hint: 'Ik hoest al … weken.',
        onSuccess: { nl: 'Dat is vervelend.', en: "That's unpleasant." },
        culturalNote: "The assistant asks questions to decide how urgent it is (triage). That's standard — not a sign they don't take you seriously.",
      },
      {
        id: 'fever',
        npc: { nl: 'Heeft u ook koorts, of bent u benauwd?', en: 'Do you also have a fever, or are you short of breath?' },
        task: 'Answer the question.',
        intents: [i('answer', 'Answer', 'ja|nee|geen|een beetje|niet')],
        modelAnswers: ['Nee, geen koorts, en ik ben niet benauwd.', 'Een beetje koorts, maar ik ben niet benauwd.'],
        hint: 'Nee, geen …',
        onSuccess: { nl: 'Oké, dan plan ik u in.', en: "Okay, then I'll book you in." },
      },
      {
        id: 'time',
        npc: { nl: 'De dokter heeft morgen om tien over elf plek. Komt dat uit?', en: 'The doctor has a slot tomorrow at ten past eleven. Does that suit you?' },
        task: 'Accept the time and thank her.',
        intents: [i('accept', 'Accept', 'ja|prima|goed|komt uit|dat kan|perfect'), i('thanks', 'Thank her', 'dank|bedankt')],
        modelAnswers: ['Ja, dat komt goed uit. Dank u wel!', 'Prima, dank u wel. Tot morgen.'],
        hint: 'Ja, dat komt …',
      },
    ],
    debrief:
      'You got your appointment! GP appointments are short (about ten minutes): write down your symptoms beforehand and bring a list of any medication you take.',
  },

  // ------------------------------------------------------------------ Work
  {
    id: 'work.interview',
    category: 'work',
    title: 'Job interview',
    level: 'B1',
    goal: 'Introduce yourself, explain your motivation and strengths, and ask a good question.',
    canDoId: 'cd.interview',
    register: 'formal',
    setting: 'A job interview for a project assistant position at a logistics company.',
    character: { name: 'Mevrouw El Amrani', role: 'HR manager' },
    goals: ['work'],
    beats: [
      {
        id: 'intro',
        npc: { nl: 'Welkom! Vertelt u eerst iets over uzelf?', en: 'Welcome! Would you start by telling us something about yourself?' },
        task: 'Briefly introduce yourself: your background and current work.',
        intents: [i('who', 'Introduce yourself', 'ik ben|ik heet|mijn naam|ik kom uit'), i('work', 'Mention your work or studies', 'werk|gewerkt|studeer|gestudeerd|ervaring|opleiding|functie')],
        modelAnswers: ['Ik ben Sam Taylor. Ik kom uit Canada en ik heb vijf jaar als planner gewerkt in de logistiek.', 'Mijn naam is Sam. Ik heb bedrijfskunde gestudeerd en ik werk nu als assistent bij een transportbedrijf.'],
        hint: 'Ik ben … en ik heb … gewerkt als …',
        onSuccess: { nl: 'Interessant.', en: 'Interesting.' },
      },
      {
        id: 'motivation',
        npc: { nl: 'Waarom solliciteert u bij ons?', en: 'Why are you applying with us?' },
        task: 'Explain why you want this job.',
        intents: [i('why', 'Give your motivation', 'omdat|want|graag|interessant|past|lijkt me|uitdaging')],
        modelAnswers: ['Omdat ik graag in een internationaal team werk en ik veel wil leren.', 'Deze functie past goed bij mijn ervaring, en uw bedrijf lijkt me heel interessant.'],
        hint: 'Omdat ik graag …',
        onSuccess: { nl: 'Duidelijk.', en: 'Clear.' },
      },
      {
        id: 'strengths',
        npc: { nl: 'Wat zijn uw sterke punten? En wat vindt u lastig?', en: 'What are your strengths? And what do you find difficult?' },
        task: 'Name a strength and a weakness — honestly, and say how you deal with it.',
        intents: [i('strength', 'Name a strength', 'sterk*|goed in|kan goed|nauwkeurig|georganiseerd|flexibel'), i('weakness', 'Name a weakness', 'lastig|moeilijk|zwak|minder goed|valkuil|werk ik aan|leer')],
        modelAnswers: ['Ik ben goed in plannen en ik werk nauwkeurig. Soms vind ik het lastig om nee te zeggen, maar daar werk ik aan.', 'Mijn sterke punt is dat ik georganiseerd ben. Mijn Nederlands is nog niet perfect, maar ik leer elke dag.'],
        hint: 'Ik ben goed in … Soms vind ik het lastig om …',
        onSuccess: { nl: 'Mooi, een eerlijk antwoord.', en: 'Nice, an honest answer.' },
        culturalNote: "Dutch interviewers value honesty and self-reflection. 'I have no weaknesses' comes across badly; a real weakness plus what you do about it works well.",
      },
      {
        id: 'question',
        npc: { nl: 'Heeft u zelf nog vragen voor ons?', en: 'Do you have any questions for us?' },
        task: 'Ask a relevant question about the job or the team.',
        intents: [i('ask', 'Ask a question', 'hoe|wat|wanneer|welke|hoeveel|is er|zijn er|kan ik')],
        modelAnswers: ['Ja, hoe ziet een normale werkdag eruit?', 'Hoe groot is het team, en wanneer hoor ik van u?'],
        hint: 'Ja, hoe ziet …?',
      },
    ],
    debrief:
      "Well done! Dutch interviews feel informal but are thorough. Next steps are often a second interview and a salary discussion — where it's normal to name a figure and negotiate politely.",
  },
  {
    id: 'work.first-day',
    category: 'work',
    title: 'First day: coffee-machine chat',
    level: 'A2',
    goal: 'Introduce yourself, ask about lunch and make a plan.',
    canDoId: 'cd.office',
    register: 'informal',
    setting: 'Your first day at a design agency in Rotterdam. At the coffee machine you meet Mila.',
    character: { name: 'Mila', role: 'New colleague' },
    goals: ['work'],
    beats: [
      {
        id: 'intro',
        npc: { nl: 'Hé, jij bent nieuw, toch? Ik ben Mila.', en: "Hey, you're new, right? I'm Mila." },
        task: 'Introduce yourself and say what your role is.',
        intents: [i('name', 'Say your name', 'ik ben|ik heet'), i('role', 'Say your role', 'werk|designer|ontwerper|stagiair|begin|functie|nieuwe|developer|ontwikkelaar|marketing')],
        modelAnswers: ['Ja, klopt! Ik ben Sam, ik begin vandaag als designer.', 'Hoi Mila, ik ben Sam. Ik ben de nieuwe ontwikkelaar.'],
        hint: 'Ja! Ik ben … en ik …',
        onSuccess: { nl: 'Welkom!', en: 'Welcome!' },
      },
      {
        id: 'lunch',
        npc: { nl: 'Weet je al hoe het hier werkt met de lunch?', en: 'Do you know how lunch works here yet?' },
        task: 'Say no and ask how it works or what time lunch is.',
        intents: [i('ask', 'Ask about lunch', 'hoe laat|hoe werkt|waar|wanneer|lunch')],
        modelAnswers: ['Nee, nog niet. Hoe laat lunchen jullie?', 'Nee, hoe werkt dat hier?'],
        hint: 'Nee, nog niet. Hoe laat …?',
        onSuccess: { nl: "Om half één, met z'n allen aan de lange tafel. Iedereen neemt zijn eigen brood mee.", en: 'At half past twelve, all together at the long table. Everyone brings their own bread.' },
      },
      {
        id: 'plan',
        npc: { nl: 'Zullen we straks samen gaan?', en: 'Shall we go together later?' },
        task: 'Accept the invitation.',
        intents: [i('accept', 'Accept', 'ja|leuk|graag|gezellig|goed idee|zeker')],
        modelAnswers: ['Ja, leuk! Graag.', 'Goed idee, gezellig!'],
        hint: 'Ja, …!',
      },
    ],
    debrief:
      'Great start! Joining the shared lunch is one of the best ways to integrate at a Dutch workplace — and to practise Dutch in a relaxed setting.',
  },
  {
    id: 'work.meeting',
    category: 'work',
    title: 'Team meeting: update and solution',
    level: 'B1',
    goal: 'Give a short update, explain the problem, propose a solution and agree on next steps.',
    canDoId: 'cd.meeting',
    register: 'neutral',
    setting: 'The weekly team meeting. Your part of the project is behind schedule.',
    character: { name: 'Linda', role: 'Team leader' },
    goals: ['work'],
    beats: [
      {
        id: 'update',
        npc: { nl: 'Sam, hoe staat het met jouw deel van het project?', en: 'Sam, how is your part of the project going?' },
        task: "Give an update: say you're behind schedule and why.",
        intents: [i('status', 'Say you are behind', 'achter|vertraging|niet af|later|niet klaar'), i('reason', 'Give a reason', 'omdat|want|door|doordat')],
        modelAnswers: ['Ik loop een week achter, omdat de leverancier te laat was.', 'We hebben wat vertraging, want ik wacht nog op informatie van de klant.'],
        hint: 'Ik loop … achter, omdat …',
        onSuccess: { nl: 'Oké, dank je voor je eerlijkheid.', en: 'Okay, thanks for being honest.' },
      },
      {
        id: 'propose',
        npc: { nl: 'Wat stel je voor?', en: 'What do you propose?' },
        task: 'Propose a solution.',
        intents: [i('propose', 'Propose a solution', 'stel voor|voorstel|zullen we|kunnen we|ik zou|misschien')],
        modelAnswers: ['Ik stel voor dat Tom mij deze week helpt, dan zijn we vrijdag klaar.', 'Misschien kunnen we de deadline een week opschuiven.'],
        hint: 'Ik stel voor dat …',
        onSuccess: { nl: 'Klinkt redelijk.', en: 'Sounds reasonable.' },
      },
      {
        id: 'agree',
        npc: { nl: 'Tom vindt het goed. Dus, wie doet wat?', en: "Tom's fine with it. So, who does what?" },
        task: 'Summarise who does what.',
        intents: [i('summary', 'Summarise the agreement', 'ik|tom|afgesproken|dus|samen')],
        modelAnswers: ['Dus afgesproken: Tom helpt mij met de planning, en ik stuur vrijdag de update naar de klant.', 'Oké: ik maak de planning en Tom belt de leverancier.'],
        hint: 'Dus afgesproken: …',
      },
    ],
    debrief:
      "Nicely done. Admitting a delay early is respected in Dutch teams — hiding it is not. Summarising 'wie doet wat' at the end is classic polder-model practice.",
  },
];

export function getScenario(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id);
}
